/** THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 * instead, edit `.graphql` files and run graphql-codegen script
 * for this file to be re-created */

import * as Types from '../../graphql/types.generated';

import { api } from '../../graphql/api';
export type GetStatusQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetStatusQuery = { __typename?: 'RootQuery', user: { __typename?: 'User', status: string } };


export const GetStatusDocument = `
    query GetStatus {
  user {
    status
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    GetStatus: build.query<GetStatusQuery, GetStatusQueryVariables | void>({
      query: (variables) => ({ document: GetStatusDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useGetStatusQuery, useLazyGetStatusQuery } = injectedRtkApi;

