/** THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 * instead, edit `.graphql` files and run graphql-codegen script
 * for this file to be re-created */

import * as Types from '../../graphql/types.generated';

import { api } from '../../graphql/api';
export type UpdateStatusMutationVariables = Types.Exact<{
  status: Types.Scalars['String'];
}>;


export type UpdateStatusMutation = { __typename?: 'RootMutation', updateStatus: { __typename?: 'User', status: string } };


export const UpdateStatusDocument = `
    mutation UpdateStatus($status: String!) {
  updateStatus(status: $status) {
    status
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    UpdateStatus: build.mutation<UpdateStatusMutation, UpdateStatusMutationVariables>({
      query: (variables) => ({ document: UpdateStatusDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useUpdateStatusMutation } = injectedRtkApi;

