/** THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 * instead, edit `.graphql` files and run graphql-codegen script
 * for this file to be re-created */

import * as Types from '../../graphql/types.generated';

import { api } from '../../graphql/api';
export type CreatePostMutationVariables = Types.Exact<{
  title: Types.Scalars['String'];
  imageUrl: Types.Scalars['String'];
  content: Types.Scalars['String'];
}>;


export type CreatePostMutation = { __typename?: 'RootMutation', createPost: { __typename?: 'Post', _id: string, title: string, imageUrl: string, content: string, createdAt: string, updatedAt: string, creator: { __typename?: 'User', name: string } } };


export const CreatePostDocument = `
    mutation CreatePost($title: String!, $imageUrl: String!, $content: String!) {
  createPost(postInput: {title: $title, imageUrl: $imageUrl, content: $content}) {
    _id
    title
    imageUrl
    content
    creator {
      name
    }
    createdAt
    updatedAt
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    CreatePost: build.mutation<CreatePostMutation, CreatePostMutationVariables>({
      query: (variables) => ({ document: CreatePostDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useCreatePostMutation } = injectedRtkApi;

