/** THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 * instead, edit `.graphql` files and run graphql-codegen script
 * for this file to be re-created */

import * as Types from '../../graphql/types.generated';

import { api } from '../../graphql/api';
export type DeletePostMutationVariables = Types.Exact<{
  id: Types.Scalars['ID'];
}>;


export type DeletePostMutation = { __typename?: 'RootMutation', deletePost?: boolean };


export const DeletePostDocument = `
    mutation DeletePost($id: ID!) {
  deletePost(id: $id)
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    DeletePost: build.mutation<DeletePostMutation, DeletePostMutationVariables>({
      query: (variables) => ({ document: DeletePostDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useDeletePostMutation } = injectedRtkApi;

